/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MiddotTimer {}
  interface MiddotTimerAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'MiddotTimer': Components.MiddotTimer;
  }

  interface StencilIntrinsicElements {
    'middot-timer': Components.MiddotTimerAttributes;
  }


  interface HTMLMiddotTimerElement extends Components.MiddotTimer, HTMLStencilElement {}
  var HTMLMiddotTimerElement: {
    prototype: HTMLMiddotTimerElement;
    new (): HTMLMiddotTimerElement;
  };

  interface HTMLElementTagNameMap {
    'middot-timer': HTMLMiddotTimerElement
  }

  interface ElementTagNameMap {
    'middot-timer': HTMLMiddotTimerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
